apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
      protocol: TCP
  selector:
    app: prometheus-persistant